version: '2.1'
orbs:
  codecov: codecov/codecov@3.1.1
jobs:
  build:
    working_directory: ~/webbclient
    # docker:
    #   - image: circleci/node:latest
    steps:
      - checkout
      - codecov/upload:
          file: ./coverage/lcov.info
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test
